# Travis CI configured to build java 8 project using gradle.
# https://travis-ci.org/
language: java

dist: trusty
sudo: required

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install: []

script: ./gradlew build

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

notifications:
  email:
    recipients:
      - dzafar.sadik@gmail.com
    on_success: change
    on_failure: always
