# ---------------------------------
# Default configuration shared by all spring profiles
# ---------------------------------
server:
  port: ${PORT:8080}
  #Disable default (whitelabel) error page
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

spring:
  # Disable spring banner
   main:
    banner-mode: 'off'
