# ---------------------------------
# Default configuration shared by all spring profiles
# ---------------------------------
server:
  port: ${PORT:8080}
  tomcat:
    max-threads: 50
  #Disable default (whitelabel) error page
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never

spring:
  mvc:
    # Disable default spring favicon
    favicon:
      enabled: false
  # Disable spring banner
  main:
    banner-mode: 'off'
