# ---------------------------------
# Development environment configuration
# ---------------------------------
spring:
  # Disable template cache
  thymeleaf:
    cache: false

logging:
  level:
    root: debug