# Vagrant automates setup of development environment in a virtual machine.
# https://docs.vagrantup.com
# https://vagrantcloud.com/search
Vagrant.configure("2") do |config|
    # Box configuration
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_check_update = false
    config.vm.hostname = 'weewarmaps.com'

    # VirtualBox specific configuration
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3000 #MB
        vb.cpus = 2
    end

    # Expose box configuration
    config.vm.synced_folder ".", "/box_config/"

    # Create a private network, which allows host-only access to the machine using a specific IP address.
    config.vm.network "private_network", ip: "192.168.33.101"

    # Configure 'vagrant-hostmanager' plugin or display warning message and instructions.
    # The plugin will manage system host file so that we can use http://weewarmaps.com instead of box ip address.
    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.manage_guest = false
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline = true
    else
        warn <<-HOST_MANAGER_NOT_INSTALLED
        WARNING!
        Plugin vagrant-hostmanager is not installed. It's goal is to manage host files on host and guest machines.

        Install the plugin:
        vagrant plugin install vagrant-hostmanager

        Alternatively, manually add the following line to the system host file:
        192.168.33.101  weewarmaps.com

        linux, mac: /etc/hosts
        windows:    C:\Windows\System32\drivers\etc

        Plugin site: https://github.com/devopsgroup-io/vagrant-hostmanager

        HOST_MANAGER_NOT_INSTALLED
   end

    # Enable provisioning with shell scripts.
    [   "install_scripts/java.sh",
        "install_scripts/elasticsearch.sh",
        "install_scripts/mongodb.sh",
        "install_scripts/nginx.sh",
        "install_scripts/utilities.sh"
    ].each do |script_path|
        config.vm.provision "shell", path: script_path
    end
end
