name: Multiplatform Java CI Workflow

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run tests with Gradle wrapper
      run: ./gradlew test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: Build a multiplatform docker image and push it to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/weewar-map-viewer:latest
